# Generated by Django 4.1 on 2022-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_subject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
        migrations.AddField(
            model_name='card',
            name='subject',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
