# Generated by Django 4.1 on 2022-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_box_question_subject_card_box_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='boxes', to='flashcards.card'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='boxes',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='flashcards.box'),
        ),
    ]
