# Generated by Django 4.1 on 2022-08-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_box_cards_alter_subject_boxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'boxes'},
        ),
    ]
