# Generated by Django 4.1 on 2022-08-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_box_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='name',
        ),
    ]
