# Generated by Django 4.1 on 2022-08-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_remove_box_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
